
Load the dataset and relevant R pacakges

```{r eval=FALSE}

# conda activate cicero
library(Seurat)
library(Signac)
library(tidyverse)
library(viridis)
library(cowplot)
library(ggrepel)
library(GenomicRanges)
theme_set(theme_cowplot())

setwd('~/swaruplab/smorabit/analysis/PiD_2021/intro')

data_dir <- 'data/'
fig_dir <- 'figures/'

# load the PiD + AD seurat_obj object
seurat_obj <- readRDS(file='/dfs3b/swaruplab/smorabit/analysis/PiD_2021/data/PiD_AD_integrated_in_progress_11-01-21.rds')


# fix some of the meta-data that was different between the two studies
seurat_obj$Diagnosis <- ifelse(seurat_obj$Dataset == 'AD', seurat_obj$Diagnosis, seurat_obj$DX)
seurat_obj$Diagnosis <- ifelse(seurat_obj$Diagnosis == "Pick's disease", 'PiD', seurat_obj$Diagnosis)


# add the UMAP coordinates:
seurat_obj$UMAP_1 <- seurat_obj@reductions$umap@cell.embeddings[,1]
seurat_obj$UMAP_2 <- seurat_obj@reductions$umap@cell.embeddings[,2]



# Diagnosis
# Sex
# Age
seurat_obj@meta.data %>% subset(Diagnosis == "PiD") %>% .$SampleID %>% table
seurat_obj@meta.data %>% subset(Diagnosis == "PiD") %>% .$celltype %>% table
seurat_obj@meta.data %>% subset(Diagnosis == "PiD") %>% .$cluster_name %>% table
seurat_obj@meta.data %>% subset(Dataset == "PiD") %>% .$Diagnosis %>% table
seurat_obj@meta.data %>% subset(Dataset == "AD") %>% .$Diagnosis %>% table
seurat_obj$celltype %>% table

umap_theme <- theme(
  axis.line=element_blank(),
  axis.text.x=element_blank(),
  axis.text.y=element_blank(),
  axis.ticks=element_blank(),
  axis.title.x=element_blank(),
  axis.title.y=element_blank(),
  panel.background=element_blank(),
  panel.border=element_blank(),
  panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  plot.background=element_blank(),
  plot.title = element_text(hjust = 0.5)
)

load('/dfs3b/swaruplab/smorabit/analysis/AD_NucSeq_2019/batch_correction/liger/update/celltype-analysis/data/color_scheme.rda')
load('~/swaruplab/smorabit/analysis/AD_NucSeq_2019/atac_analysis/all_data/celltype-analysis/data/color_scheme.rda')

color_scheme_snATAC_celltype$EX <- 'turquoise'

```

Test DA peaks for astrocytes

```{r eval=FALSE}

DefaultAssay(seurat_obj) <- 'peaks'
Idents(seurat_obj) <- ifelse(seurat_obj$celltype == 'ASC', 'ASC', 'Rest')

da_peaks <- FindMarkers(
  object = seurat_obj,
  ident.1 = "ASC",
  ident.2 = "Rest",
  min.pct = 0.05,
  test.use = 'LR',
  logfc.threshold = 0.1,
#  latent.vars = 'peak_region_fragments'
)


seurat_subset <- seurat_obj %>% subset(celltype =='EX' & Dataset == 'PiD')

Idents(seurat_subset) <- as.factor(seurat_subset$Diagnosis)


da_peaks_pid <- FindMarkers(
  object = seurat_subset,
  ident.1 = "Control",
  ident.2 = "PiD",
  min.pct = 0.05,
  test.use = 'LR',
  logfc.threshold = 0.1,
  latent.vars = 'nCount_peaks'
)


```

co-access


```{r eval=FALSE}

load("/dfs3b/swaruplab/zechuas/Projects/PiD_2021/scATAC_data/Analysis/Cis_regulatory_network/PiDnControl/ASC_cicero_connections.rda")

load("/dfs3b/swaruplab/smorabit/analysis/AD_NucSeq_2019/atac_analysis/all_data/cicero/update/data/ASC_cicero_connections.rda")

```
