###====================================
### NOTE : Date - 11/11/2022
###====================================

# Project: Pick's Disease + AD
# @Ze

# https://www.cog-genomics.org/plink/2.0/

# https://zenodo.org/record/3359882#.Y2FVdezMITv
# The 1000 Genomes Project Consortium. (2019). 1000 Genomes Project (1.0) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.3359882

###====================================
# NOTE: PLINK_vcf_to_bed


# NOTE AD GWAS SNPs
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_1_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr1.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_2_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr2.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr3.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_3_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr3.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_4_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr4.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr5.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_5_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr5.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_6_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr6.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_7_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr7.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_8_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr8.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_9_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr9.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_10_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr10.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_11_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr11.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_12_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr12.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr13.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_13_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr13.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr14.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_14_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr14.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_15_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr15.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr16.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_16_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr16.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr17.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_17_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr17.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_18_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr18.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr19.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_19_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr19.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_20_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr20.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_21_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr21.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract AD_SNPs_bychr/AD_GWAS_22_SNPs.txt --make-bed --max-alleles 2 --out AD_SNPs_bedfiles/AD_GWAS.chr22.phase3_shapeit2_mvncall_integrated_v5a


# NOTE FTD GWAS SNPs
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_1_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr1.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr2.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_2_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr2.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr3.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_3_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr3.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_4_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr4.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr5.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_5_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr5.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr6.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_6_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr6.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr7.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_7_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr7.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_8_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr8.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_9_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr9.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr10.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_10_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr10.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr11.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_11_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr11.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_12_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr12.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr13.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_13_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr13.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr14.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_14_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr14.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr15.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_15_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr15.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr16.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_16_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr16.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr17.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_17_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr17.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_18_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr18.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr19.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_19_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr19.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_20_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr20.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_21_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr21.phase3_shapeit2_mvncall_integrated_v5a
/dfs7/swaruplab/zechuas/tools_software/PLINK/plink2 --vcf /dfs7/swaruplab/zechuas/resources/1000Genomes/Phase3_v5a/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz --extract FTD_SNPs_bychr/FTD_GWAS_22_SNPs.txt --make-bed --max-alleles 2 --out FTD_SNPs_bedfiles/FTD_GWAS.chr22.phase3_shapeit2_mvncall_integrated_v5a
